version: '3.5'
services:
  api:
    container_name: api-service
    image: woaiso/wst-service
    depends_on:
      - mongodb
    ports:
      - 7001:7001
    links:
      - mongodb
    environment:
      - PORT=7001

  mongodb:
    container_name: api-mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  nginx:
    container_name: nginx
    image: woaiso/docker-tengine
    depends_on:
      - mongodb
      - api
    links:
      - api
    ports:
      - '80:80'
      - '443:443'
