version: '3.7'
services:
  api:
    container_name: api-service
    image: woaiso/wst-service
    depends_on:
      - mongodb
    ports:
      - 7001:7001
    links:
      - mongodb
    environment:
      - PORT=7001

  mongodb:
    container_name: api-mongodb
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017

  image:
    container_name: api-image
    image: woaiso/wst-image
    ports:
      - 5000:5000

  nginx:
    container_name: nginx
    image: woaiso/docker-tengine:2.0
    volumes:
      - ./sites_conf:/etc/nginx/sites-enabled
      - ./www:/data/www
      - ./ssl:/data/ssl
    depends_on:
      - mongodb
      - api
      - image
      - registry
    links:
      - api
      - image
      - registry
    ports:
      - '80:80'
      - '443:443'
  registry:
    container_name: registry-hub
    image: registry:2
    volumes:
      - ./registry:/var/lib/registry
    ports:
      - 5001:5001
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5001