version: '3.9'
services:
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_USER=${MYSQL_USER}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
        ports:
            - '3307:3306'
    redis:
        image: 'redis:5.0.14'
        command: --requirepass $REDIS_PASSWORD --appendonly yes
        volumes:
            - ./redis:/data
        ports:
            - '6380:6379'
    mongo:
        image: 'mongo:5.0.5'
        restart: always
        volumes:
            - ./mongo:/data/db
        environment:
            - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}'
            - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}'
            - 'MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}'
        ports:
            - '27018:27017'
    shark-server:
        image: 'shark-server:latest'
        restart: always
        volumes:
            - type: bind
              source: ./shark-server/.env
              target: /usr/src/app/dist/.env
    nginx:
        image: 'woaiso/docker-tengine:2.1.5'
        restart: always
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
            - ./sites_conf:/etc/nginx/sites-enabled
            - ./www:/usr/share/nginx/html
            - ./ssl:/etc/nginx/key
            - ./logs/nginx:/var/log/nginx
        ports:
            - '80:80'
            - '443:443'
        healthcheck:
            test: ['CMD', 'curl', '--fail', 'http://nginx/server-status']
            interval: 1m30s
            timeout: 10s
            retries: 5
