version: '3.9'
services:
    nginx:
        image: woaiso/docker-tengine:2.1.5
        volumes:
            - ./sites_conf:/etc/nginx/
            - ./ssl:/etc/nginx/key
            - ./logs/nginx:/var/log/nginx
        links:
            - mysql
        ports:
            - '443:443'
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_USER=${MYSQL_USER}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'