version: '3.9'
services:
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_USER=${MYSQL_USER}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
        ports:
            - '3307:3306'
    redis:
        image: 'redis:5.0.14'
        command: --requirepass $REDIS_PASSWORD --appendonly yes
        volumes:
            - ./redis:/data
        ports:
            - '6380:6379'
