version: '3.9'
services:
    mysql:
        image: mysql:5.7
        platform: linux/x86_64
        command: 
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
            --max_allowed_packet=128M
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        environment:
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_USER=${MYSQL_USER}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
            - 'TZ=Asia/Shanghai'
        ports:
            - '3307:3306'
    redis:
        image: 'redis:5.0.14'
        command: --requirepass $REDIS_PASSWORD --appendonly yes
        volumes:
            - ./redis:/data
            - /etc/localtime:/etc/localtime
        ports:
            - '6380:6379'
    mongo:
        image: 'mongo:5.0.5'
        restart: always
        volumes:
            - ./mongo:/data/db
            - /etc/localtime:/etc/localtime
        environment:
            - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}'
            - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}'
            - 'MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}'
        ports:
            - '27018:27017'
    shark-server:
        build: 
            context: ./../../zhibo-shark
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime
            - type: bind
              source: ./shark-server/.env
              target: /usr/src/app/.env
    nginx:
        entrypoint: ["echo", "Service nginx disabled"]
        image: 'woaiso/docker-tengine:2.1.5'
        restart: 'no'
        volumes:
            - type: bind
              source: ./nginx/nginx.conf
              target: /etc/nginx/nginx.conf
            - ./sites_conf:/etc/nginx/sites-enabled
            - ./www:/usr/share/nginx/html
            - ./ssl:/etc/nginx/key
            - ./logs/nginx:/var/log/nginx
        ports:
            - '80:80'
            - '443:443'
        healthcheck:
            test: ['CMD', 'curl', '--fail', 'http://nginx/server-status']
            interval: 1m30s
            timeout: 10s
            retries: 5
