services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - ./volumes/db/pgdata:/var/lib/postgresql/data
        restart: unless-stopped
    rabbitmq:
        image: rabbitmq:4.1.0-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        ports:
            - '${RABBITMQ_MANAGEMENT_PORT}:15672'
            - '${RABBITMQ_PORT}:5672'
        volumes:
            - ./volumes/mq/rbdata:/var/lib/rabbitmq
        restart: unless-stopped
    minio:
        image: minio/minio
        container_name: minio
        volumes:
            - './volumes/minio:/data'
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        ports:
            - '${MINIO_PORT}:9000'
            - '${MINIO_MANAGEMENT_PORT}:9001'
        restart: always
        command: >
            server /data --address ":${MINIO_PORT}" --console-address ":${MINIO_MANAGEMENT_PORT}"
