---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
## X-Pack security credentials
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USER}
xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
